### ISSUE TITLE
Install task missing fetch variables

### ISSUE THREAD

**Issue by hstaab** [mtomov/capistrano-good-job#1]
Hello Martin

I was following the Readme instructions for installing the gem but came across issues from line 9 in good_job.rake:
`execute :mkdir, "-p", fetch(:systemd_conf_dir)`

`fetch(:systemd_conf_dir)` never resolves to anything so mkdir fails.

Are these fetch variables expected to be set already? Are the provided by a different plugin? I ended up getting it going by simply replacing them with expected values.

Also is `fetch(:systemd_conf_dir)` any different from `fetch(:good_job_systemd_conf_dir)` in the same file?

Thanks in advance!

**Comment by mtomov** [comment]
Hey @hstaab , thanks so much for reporting this!

It was indeed an error, and `systemd_conf_dir` was meant to say  `good_job_systemd_conf_dir`. Good call on that!

I've fixed this, and [released a new patch version](https://github.com/mtomov/capistrano-good-job/releases/tag/v.0.1.1) of the gem in Rubygems.
